export const items = [
    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
	    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
	    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
	    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
	    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
	    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
	    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
	    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
		    {
        "cloud": "Azure",
        "name": "WIN10",
        "status": "deallocating",
        "size": "Standard_D2",
        "cpu": 2,
        "mem": "7 GiB",
        "nicPrivateIpAddress": "00.0.0.0",
        "nicPublicIpAddress": "00.000.000.00",
        "lbPrivateIpAddress": null,
        "lbPublicIpAddress": "",
        "region": "eastus",       
        "operationSystem": "Windows"
    },
]